export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'home',
    path: '/home',
    title: '首页',
    icon: 'icon-park-outline:home',
    isKeepAlive: false,
    isHide: false,
    type: 1,
    componentPath: '/home/index.vue',
    id: '1',
    parentId: null,
  },
  {
    name: 'settings',
    path: '/settings',
    title: '设置中心',
    icon: 'icon-park-outline:setting',
    isKeepAlive: true,
    isHide: false,
    type: 1,
    componentPath: null,
    id: '3',
    parentId: null,
  },
  {
    name: 'menu',
    path: '/settings/menu',
    title: '菜单管理',
    icon: 'icon-park-outline:every-user',
    isKeepAlive: true,
    isHide: false,
    type: 2,
    componentPath: '/settings/menu/index.vue',
    id: '4',
    parentId: '3',
  },
  {
    name: 'menu1',
    path: '/settings/menu1',
    title: '菜单嵌套',
    icon: 'icon-park-outline:every-user',
    isKeepAlive: true,
    isHide: false,
    type: 1,
    componentPath: '/settings/menu/index.vue',
    id: '5',
    parentId: '3',
  },
  {
    name: 'menu2',
    path: '/settings/menu2',
    title: '菜单嵌套1',
    icon: 'icon-park-outline:every-user',
    isKeepAlive: true,
    isHide: false,
    type: 1,
    componentPath: null,
    id: '6',
    parentId: '5',
  },
  {
    name: 'menu3',
    path: '/settings/menu3',
    title: '菜单嵌套2',
    icon: 'icon-park-outline:every-user',
    isKeepAlive: true,
    isHide: false,
    type: 2,
    componentPath: '/settings/menu/index.vue',
    id: '7',
    parentId: '6',
  },
];
