<script setup lang="ts">
defineOptions({ name: 'Home' });
</script>

<template>
  <div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
    <div>首页</div>
  </div>
</template>
